const truth = [
    "I'm doing great!",
    "I am worthy of success", 
    "I am a good person",
    "the poeple around me want to see me succeed",
    "I'll figure this all out",
    "Asking for help is a sign of self-respect and self-awareness",
    "I am growing and I am going at my own pace",
    "I am good and getting better", 
    "I am loved and worthy", 
    "I am optimistic because today is a new day",
    "I am still learning so it’s okay to make mistakes", 
    "I am valued and helpful",
    "I can control how I respond to things that are confronting me",
    "I celebrate the good qualities in others and myself", 
    "I do not pretend to be anyone or anything other than who I am",
    "I have everything I need to succeed",
    "I hold wisdom beyond knowledge",
    "I let go of the things that sit achingly out of reach",
    "My life is not a race or competition",
    "My weirdness is wonderful", 
    "Sometimes the work is resting", 
    "Taking a break can be part of the solution",
    "people like me",
    "I deserve to be kind to myself",
    "There is growth in stillness", 
    "There is poetry in everything, and I am looking for it", 
    "Today is an opportunity to grow and learn",
    "When I speak my needs, I receive them abundantly", 
    "I am good at solving problems", 
    "Making mistakes helps me grow", 
    "I don’t have to be perfect to be worthy", 
    "I’m proud of myself, I recognize my worth",
    "I am supposed to be here",
    "they chose me for this task because they know I am worthy",
    "I can learn anything I put my mind to", 
    "I can work hard to achieve my goals", 
    "Asking for advice improves my capabilities",
    "I am not in competition with anyone but myself",
    "I can ask for support", 
    "I believe in myself", 
    "I’m fun to be around", 
    "I make a difference in the world by simply existing in it",
    "I am not an imposter, I am supposed to be here",
    "there are not things I can’t do, there are only things I can't do... yet",
    "I am grateful to be where I am",
    "I have everything I need to change my circumstances",
    "I am capable",
    "I am not afraid of failure",
    "when I find out I am wrong, I am happy to have a new opportunity to learn",
    "I am as happy on the journey to my goals, as I am when I reach them",
    "my colleagues believe in me",
]

//this
module.exports = truth;